# This workflow is named "Node.js CI with Webpack"
name: Node.js CI with Webpack

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Triggers the workflow on pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Defines a matrix of configurations to run the job with
    strategy:
      matrix:
        # Specifies the Node.js versions to test against.
        # This will run the job three times, once for each version.
        node-version: [18.x, 20.x, 22.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # 1. Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Sets up the specified version of Node.js from the matrix
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        # Caches npm dependencies for faster subsequent builds
        cache: 'npm'

    # 3. Installs dependencies and runs the build script
    - name: Install dependencies and build
      run: |
        npm ci
        npm run build
